# Generated by Django 4.0.6 on 2023-11-24 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('ft_boleto', models.ImageField(blank=True, null=True, upload_to='Balancete_imgs/')),
                ('data', models.DateTimeField(null=True, verbose_name='Data de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('valor', models.FloatField(default=0.0)),
                ('balancete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Financeiro.balancete')),
            ],
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('valor', models.FloatField(default=0.0)),
                ('balancete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Financeiro.balancete')),
            ],
        ),
        migrations.AddField(
            model_name='balancete',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Financeiro.usuario'),
        ),
    ]
