# Generated by Django 4.0.6 on 2023-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0002_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='Data referente a despesa'),
        ),
        migrations.AddField(
            model_name='receitas',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='Data referente a receita'),
        ),
        migrations.AlterField(
            model_name='balancete',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='Data do balanço mensal'),
        ),
    ]
