# Generated by Django 4.0.6 on 2023-12-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0007_rename_despesas_despesa_rename_receitas_receita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_nasc',
            field=models.DateTimeField(null=True, verbose_name='Data de nascimento'),
        ),
    ]
